
// layout.js
import { ChakraProvider } from "@chakra-ui/react";
import { WebRtcProvider } from "@/contexts/WebRtcContext";
import { LoadingProvider } from "@/contexts/LoadingContext";
import { IpfsProvider } from "@/contexts/IpfsContext";
import Load from "@/components/LoadComponent";
import '@/styles/globals.css';
import theme from "@/styles/theme";
import '@fontsource/lexend-deca';

export const metadata = {
  title: "skyShare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ChakraProvider theme={theme}>
        <WebRtcProvider>
        <IpfsProvider>
        <LoadingProvider>
          <div>
            <Load />
            {/* Render children here to maintain existing content */}
            {children}
          </div>
        </LoadingProvider>
        </IpfsProvider>
        </WebRtcProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
