
// layout.js
import { ChakraProvider } from "@chakra-ui/react";
import theme from "@/styles/theme";
import FileUpload from "@/components/FileUpload"; // Adjust the path as necessary

export const metadata = {
  title: "skyShare",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ChakraProvider theme={theme}>
          <div>
            {/* You can place the FileUpload component here */}
            <FileUpload />
            {/* Render children here to maintain existing content */}
            {children}
          </div>
        </ChakraProvider>
      </body>
    </html>
  );
}
