name: Deploy Chrome Extension
on:
  push:
    tags:
      - 'v*'  # version tags: v1.0.0, v2.1.3, etc.
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
      REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
      REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        working-directory: browser-ext
        run: yarn install --frozen-lockfile
      - name: Build extension
        working-directory: browser-ext
        run: yarn build
      - name: Zip build folder
        run: |
          cd browser-ext/build
          zip -r ../chrome-extension.zip .
      - name: Extract release notes from CHANGELOG.md
        run: |
          VERSION="${{ github.ref_name }}"  # e.g., v1.1.0
          sed -n "/## $VERSION/,/^---/p" browser-ext/CHANGELOG.md | sed '$d' > RELEASE_NOTES.md
        shell: bash
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          body_path: RELEASE_NOTES.md
          files: browser-ext/chrome-extension.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
